<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <AssemblyName>TD2-Dumper</AssemblyName>
    <RootNamespace>TD2Dumper</RootNamespace>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <Platforms>x64</Platforms>
    <ApplicationIcon>division2.ico</ApplicationIcon>
    <TrimMode>full</TrimMode>
    <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.*" />
  </ItemGroup>
</Project>
